[versions]

# general
lombok = "1.18.42"
jetbrains-annotations = "26.0.2"

# database
jdbi = "3.50.0"

[libraries]

# general
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

# database
jdbi-core = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
jdbi-sqlobject = { group = "org.jdbi", name = "jdbi3-sqlobject", version.ref = "jdbi" }